### ISSUE TITLE
XcodeCloudでのビルドが通らない

### ISSUE THREAD

**Issue by SNQ-2001** [cybozu/LicenseList#14]
LicenseListをRun Build Tool Plug-inに追加すると発生する

IDESkipPackagePluginFingerprintValidatationは設定済み
```ci_post_clone.sh
defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
```

# エラー内容
```
Command exited with non-zero exit-code: 65
```

# 参考

以下のライブラリだとXcodeCloudのビルドは通る
https://github.com/zunda-pixel/LicenseProvider/

ここで発見した
https://twitter.com/d_date/status/1671347277489917953

**Comment by Kyome22** [comment]
@SNQ-2001 Thank you for reporting the issue! I'll investigate.

**Comment by Kyome22** [comment]
zunda-pixel/LicenseProvider との違いは plistとして出力しているかswiftファイルとして出力しているかだけで、他はplugin的な側面だと同じ。swiftファイルだと問題が起きづらいというのは既知なので、swiftファイルとして出力するというのはありかもしれない。

The only difference from zunda-pixel/LicenseProvider is whether it is output as a plist or a swift file, and the other aspects are the same as plugins. It is known that problems are less likely to occur with swift files, so outputting as a swift file may solve the problem.

**Comment by Kyome22** [comment]
@SNQ-2001 
お待たせしました。 #24 で生成するファイルをplistからswiftに変更したため、Xcode Cloudでも動くようになりました。

Sorry I made you wait. By changing #24, the generated file was changed from plist to swift, so it now works on Xcode Cloud.

**Comment by SNQ-2001** [comment]
@Kyome22 
ありがとうございます！！

**Comment by crane-hiromu** [comment]
@Kyome22 
今のバージョン(0.6.0)を入れてみたのですが、手元でこんな感じになってしまったので共有しておきます🙏

![Screenshot 2024-03-20 at 13 38 11](https://github.com/cybozu/LicenseList/assets/24838521/48d17be8-78c5-4360-8213-980815d94341)
![Screenshot 2024-03-20 at 13 37 08](https://github.com/cybozu/LicenseList/assets/24838521/436db550-c18d-40d2-a48f-8c7821149c5f)
![Screenshot 2024-03-20 at 13 37 25](https://github.com/cybozu/LicenseList/assets/24838521/fb45ca7d-7256-42b3-9c97-eb2779480869)

もし何かこちらに落ち度があった場合はすいません🙇‍♂️
