### ISSUE TITLE
Proposal to Include URL in Library Information

### ISSUE THREAD

**Issue by SNQ-2001** [cybozu/LicenseList#20]
I want to be able to navigate to the library repository from the app side.

**Comment by Kyome22** [comment]
@SNQ-2001 
Thank you for reporting the issue.
I also checked your PR.
So, do you think `LicenseListView` should have the function to jump to the repository page by default?
Is it okay to have this function only when using Library.libraries?

**Comment by SNQ-2001** [comment]
@Kyome22 
How about having a flag like `showLibraryLinkButton` on the `LicenseListView ` so that the user can select it?

```swift
struct ContentView: View {
    var body: some View {
        NavigationView {
            LicenseListView(showLibraryLinkButton: true)
                .navigationTitle("LICENSE")
        }
    }
}
```

**Comment by Kyome22** [comment]
@SNQ-2001 
Adding a flag is a good idea, but specifying a Style may also be a good idea.
For example, something like the following one.

```swift
struct ContentView: View {
    var body: some View {
        NavigationView {
            LicenseListView()
                .licenseViewStyle(.withRepositoryAnchorLink) // or .plain
                .navigationTitle("LICENSE")
        }
    }
}
```

**Comment by SNQ-2001** [comment]
Please check the updated PR!


https://github.com/cybozu/LicenseList/assets/84154073/08d8373c-cdb6-4d65-9fa9-1139040c4676

**Comment by Kyome22** [comment]
Great job!! It looks very good.
