### ISSUE TITLE
No such module になってしまう

### ISSUE THREAD

**Issue by crane-hiromu** [cybozu/LicenseList#3]
自信のプロジェクトで使用しようとしたが `No such module` で出来ず。
確認の為、こちらのデモプロジェクトを手元でも試してみましたが、同様の現象が起きるので issue をあげておきます🙏

![](https://user-images.githubusercontent.com/24838521/188253443-f400d087-047e-45ab-a9c2-594590660496.png)

Xcode13.3
MacOS Monterey 12.5
Apple M1

**Comment by Kyome22** [comment]
@crane-hiromu 
ご連絡ありがとうございます！
手元の複数のMacでビルドを試してみました。
たしかに`No such module`になることはありますが、Reset Package Cachesすればビルドできるようになりました。
のでClone後に各個人の開発環境でPackageのキャッシュクリアをする必要があるのかもしれません。
(Package.resolvedを.gitignoreしていないのがいけないのかもしれません..）
