### ISSUE TITLE
tvOS support and style configuration

### ISSUE THREAD

**Issue by setoelkahfi** [cybozu/LicenseList#46]
Hello @Kyome22, thanks for this project. It's been useful for me.

Are you planning to support another platform? I'm working on supporting tvOS. Also, we have a slightly different design system. Do you have a plan to support customization as well? Otherwise, I'll use my fork.

**Comment by Kyome22** [comment]
@setoelkahfi Thank you for reporting this issue.
Please wait for a response as I will look into this issue within my team.

**Comment by setoelkahfi** [comment]
I have the changes ready in my fork. If you want, I can open a PR.

**Comment by setoelkahfi** [comment]
It looks great!
