### ISSUE TITLE
`LicenseListViewStyle` and `LicenseListViewStyle` usage

### ISSUE THREAD

**Issue by setoelkahfi** [cybozu/LicenseList#49]
Hello, are the `LicenseListViewStyle` and `LicenseListViewStyle` meant to be implemented by the users of this package? I just want to change the appearance of the `PlainLicenseListViewStyle` and don't feel like implementing the whole `@MainActor func makeBody(configuration: Configuration) -> Body`

**Comment by Kyome22** [comment]
@setoelkahfi Thank you for reporting the issue.
Do you mean `LicenseListViewStyle` and `LicenseViewStyle`?

Although there is a limited amount you can do, you can modify the appearance of the `PlainLicenseListViewStyle`.

```swift
struct MyLicenseListViewStyle: LicenseListViewStyle {
    func makeBody(configuration: Configuration) -> some View {
        PlainLicenseListViewStyle()
            .makeBody(configuration: configuration)
            .foregroundStyle(Color.red)
    }
}
```

<img src="https://github.com/user-attachments/assets/14c11048-66d4-4dd1-b51e-6e1f7dcf642c" width="300" />

**Comment by setoelkahfi** [comment]
I see. I'll have a look.
